import type { CatalogProduct } from "#/components/catalog/types"

export async function fetchProducts(): Promise<CatalogProduct[]> {
  return [
    {
      id: "1",
      imageUrl:
        "https://images.pexels.com/photos/5202048/pexels-photo-5202048.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes de Sol Aviator",
      brand: "Ray-Ban",
      price: 329900,
      material: "Metal",
      shape: "Aviador",
      categories: ["Gafas de sol", "Unisex"],
      badge: "NUEVO",
    },
    {
      id: "2",
      imageUrl:
        "https://images.pexels.com/photos/26575042/pexels-photo-26575042.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes Rectangulares Rosados",
      brand: "Persol",
      price: 3289900,
      material: "Acetato",
      shape: "Rectangular",
      categories: ["Marcos ópticos", "Mujer", "Premium"],
    },
    {
      id: "3",
      imageUrl:
        "https://images.pexels.com/photos/34978681/pexels-photo-34978681.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Colección Gafas Modernas",
      brand: "Oakley",
      price: 459900,
      material: "Titanio",
      shape: "Rectangular",
      categories: ["Gafas de sol", "Unisex", "Deportivas"],
      badge: "OFERTA",
    },
    {
      id: "4",
      imageUrl:
        "https://images.pexels.com/photos/15735139/pexels-photo-15735139.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes de Mercado",
      brand: "Prada",
      price: 379900,
      material: "Acetato",
      shape: "Cat Eye",
      categories: ["Marcos ópticos", "Mujer"],
    },
    {
      id: "5",
      imageUrl:
        "https://images.pexels.com/photos/2767694/pexels-photo-2767694.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Gafas de Sol Coloridas",
      brand: "Gucci",
      price: 729900,
      material: "Metal",
      shape: "Circular",
      categories: ["Gafas de sol", "Mujer"],
    },
    {
      id: "6",
      imageUrl:
        "https://images.pexels.com/photos/1013482/pexels-photo-1013482.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes de Sol Clásicos",
      brand: "Ray-Ban",
      price: 319900,
      material: "Metal",
      shape: "Aviador",
      categories: ["Gafas de sol", "Hombre", "Unisex"],
    },
    {
      id: "7",
      imageUrl:
        "https://images.pexels.com/photos/5201935/pexels-photo-5201935.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes Exhibidos en Rack",
      brand: "Ray-Ban",
      price: 499900,
      material: "Acetato",
      shape: "Rectangular",
      categories: ["Marcos ópticos", "Unisex"],
      badge: "NUEVO",
    },
    {
      id: "8",
      imageUrl:
        "https://images.pexels.com/photos/121795/pexels-photo-121795.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Gafas Reflectantes",
      brand: "Prada",
      price: 619900,
      material: "Titanio",
      shape: "Circular",
      categories: ["Gafas de sol", "Unisex", "Deportivas"],
      badge: "OFERTA",
    },
    {
      id: "9",
      imageUrl:
        "https://images.pexels.com/photos/5766156/pexels-photo-5766156.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes Marco Metálico",
      brand: "Persol",
      price: 689900,
      material: "Metal",
      shape: "Rectangular",
      categories: ["Marcos ópticos", "Hombre"],
    },
    {
      id: "10",
      imageUrl:
        "https://images.pexels.com/photos/5472300/pexels-photo-5472300.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes de Sol Azul Marino",
      brand: "Ray-Ban",
      price: 349900,
      material: "Acetato",
      shape: "Aviador",
      categories: ["Gafas de sol", "Hombre"],
    },
    {
      id: "11",
      imageUrl:
        "https://images.pexels.com/photos/3671083/pexels-photo-3671083.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Gafas Redondas Vintage",
      brand: "Vogue",
      price: 219900,
      material: "Acetato",
      shape: "Circular",
      categories: ["Gafas de sol", "Mujer", "Unisex"],
      badge: "NUEVO",
    },
    {
      id: "12",
      imageUrl:
        "https://images.pexels.com/photos/1493111/pexels-photo-1493111.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes Solares Deportivos",
      brand: "Oakley",
      price: 529900,
      material: "Titanio",
      shape: "Rectangular",
      categories: ["Gafas de sol", "Deportivas", "Unisex"],
    },
    {
      id: "13",
      imageUrl:
        "https://images.pexels.com/photos/2088164/pexels-photo-2088164.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes Elegantes Cat Eye",
      brand: "Vogue",
      price: 279900,
      material: "Acetato",
      shape: "Cat Eye",
      categories: ["Marcos ópticos", "Mujer"],
      badge: "OFERTA",
    },
    {
      id: "14",
      imageUrl:
        "https://images.pexels.com/photos/1366919/pexels-photo-1366919.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Gafas de Sol Ovaladas",
      brand: "Persol",
      price: 419900,
      material: "Metal",
      shape: "Circular",
      categories: ["Gafas de sol", "Unisex"],
    },
    {
      id: "15",
      imageUrl:
        "https://images.pexels.com/photos/947885/pexels-photo-947885.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes Minimalistas",
      brand: "Gucci",
      price: 569900,
      material: "Titanio",
      shape: "Rectangular",
      categories: ["Marcos ópticos", "Unisex", "Premium"],
      badge: "NUEVO",
    },
    {
      id: "16",
      imageUrl:
        "https://images.pexels.com/photos/1047540/pexels-photo-1047540.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes Retro Chic",
      brand: "Prada",
      price: 459900,
      material: "Acetato",
      shape: "Cat Eye",
      categories: ["Marcos ópticos", "Mujer"],
    },
    {
      id: "17",
      imageUrl:
        "https://images.pexels.com/photos/1576995/pexels-photo-1576995.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Gafas Aviador Dorado",
      brand: "Ray-Ban",
      price: 389900,
      material: "Metal",
      shape: "Aviador",
      categories: ["Gafas de sol", "Unisex", "Premium"],
      badge: "OFERTA",
    },
    {
      id: "18",
      imageUrl:
        "https://images.pexels.com/photos/2606598/pexels-photo-2606598.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes Deportivos Runner",
      brand: "Oakley",
      price: 479900,
      material: "Titanio",
      shape: "Rectangular",
      categories: ["Gafas de sol", "Deportivas", "Unisex"],
    },
    {
      id: "19",
      imageUrl:
        "https://images.pexels.com/photos/1787234/pexels-photo-1787234.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes Clásicos Carey",
      brand: "Vogue",
      price: 249900,
      material: "Acetato",
      shape: "Circular",
      categories: ["Marcos ópticos", "Unisex"],
      badge: "NUEVO",
    },
    {
      id: "20",
      imageUrl:
        "https://images.pexels.com/photos/701877/pexels-photo-701877.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes Premium Titanio",
      brand: "Gucci",
      price: 799900,
      material: "Titanio",
      shape: "Rectangular",
      categories: ["Marcos ópticos", "Unisex", "Premium"],
    },
    {
      id: "21",
      imageUrl:
        "https://images.pexels.com/photos/8989491/pexels-photo-8989491.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Gafas de Sol Carey Elegantes",
      brand: "Persol",
      price: 289900,
      material: "Acetato",
      shape: "Cat Eye",
      categories: ["Gafas de sol", "Mujer"],
      badge: "NUEVO",
    },
    {
      id: "22",
      imageUrl:
        "https://images.pexels.com/photos/26050118/pexels-photo-26050118.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes Deportivos Reflectantes",
      brand: "Oakley",
      price: 549900,
      material: "Titanio",
      shape: "Rectangular",
      categories: ["Gafas de sol", "Deportivas", "Unisex"],
    },
    {
      id: "23",
      imageUrl:
        "https://images.pexels.com/photos/10837794/pexels-photo-10837794.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Gafas Redondas Vintage Dorado",
      brand: "Vogue",
      price: 239900,
      material: "Metal",
      shape: "Circular",
      categories: ["Gafas de sol", "Unisex", "Premium"],
      badge: "OFERTA",
    },
    {
      id: "24",
      imageUrl:
        "https://images.pexels.com/photos/10837797/pexels-photo-10837797.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes Solares Cuadrados Negros",
      brand: "Ray-Ban",
      price: 369900,
      material: "Metal",
      shape: "Rectangular",
      categories: ["Gafas de sol", "Hombre"],
    },
    {
      id: "25",
      imageUrl:
        "https://images.pexels.com/photos/4784676/pexels-photo-4784676.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Marcos Ópticos Tortuga",
      brand: "Prada",
      price: 429900,
      material: "Acetato",
      shape: "Rectangular",
      categories: ["Marcos ópticos", "Unisex"],
      badge: "NUEVO",
    },
    {
      id: "26",
      imageUrl:
        "https://images.pexels.com/photos/704241/pexels-photo-704241.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Gafas Aviador Clásico Dorado",
      brand: "Ray-Ban",
      price: 349900,
      material: "Metal",
      shape: "Aviador",
      categories: ["Gafas de sol", "Hombre", "Unisex"],
    },
    {
      id: "27",
      imageUrl:
        "https://images.pexels.com/photos/5202051/pexels-photo-5202051.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes de Sol Ovalados Rosa",
      brand: "Gucci",
      price: 589900,
      material: "Acetato",
      shape: "Circular",
      categories: ["Gafas de sol", "Mujer", "Premium"],
      badge: "OFERTA",
    },
    {
      id: "28",
      imageUrl:
        "https://images.pexels.com/photos/27347004/pexels-photo-27347004.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Marcos Rectangulares Azul Marino",
      brand: "Persol",
      price: 319900,
      material: "Acetato",
      shape: "Rectangular",
      categories: ["Marcos ópticos", "Hombre"],
    },
    {
      id: "29",
      imageUrl:
        "https://images.pexels.com/photos/14090246/pexels-photo-14090246.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Gafas de Sol Espejadas Deportivas",
      brand: "Oakley",
      price: 499900,
      material: "Titanio",
      shape: "Rectangular",
      categories: ["Gafas de sol", "Deportivas", "Unisex"],
      badge: "NUEVO",
    },
    {
      id: "30",
      imageUrl:
        "https://images.pexels.com/photos/11882776/pexels-photo-11882776.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes Cat Eye Negro Brillante",
      brand: "Prada",
      price: 389900,
      material: "Acetato",
      shape: "Cat Eye",
      categories: ["Gafas de sol", "Mujer"],
    },
    {
      id: "31",
      imageUrl:
        "https://images.pexels.com/photos/29644611/pexels-photo-29644611.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Gafas Redondas Metálicas Plateadas",
      brand: "Vogue",
      price: 259900,
      material: "Metal",
      shape: "Circular",
      categories: ["Marcos ópticos", "Unisex", "Premium"],
    },
    {
      id: "32",
      imageUrl:
        "https://images.pexels.com/photos/5202049/pexels-photo-5202049.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes Solares Aviador Verde",
      brand: "Ray-Ban",
      price: 379900,
      material: "Metal",
      shape: "Aviador",
      categories: ["Gafas de sol", "Unisex"],
      badge: "OFERTA",
    },
    {
      id: "33",
      imageUrl:
        "https://images.pexels.com/photos/13430474/pexels-photo-13430474.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Marcos Ópticos Cuadrados Carey",
      brand: "Persol",
      price: 299900,
      material: "Acetato",
      shape: "Rectangular",
      categories: ["Marcos ópticos", "Hombre", "Unisex"],
      badge: "NUEVO",
    },
    {
      id: "34",
      imageUrl:
        "https://images.pexels.com/photos/13430471/pexels-photo-13430471.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Gafas de Sol Deportivas Naranja",
      brand: "Oakley",
      price: 569900,
      material: "Titanio",
      shape: "Rectangular",
      categories: ["Gafas de sol", "Deportivas", "Unisex"],
    },
    {
      id: "35",
      imageUrl:
        "https://images.pexels.com/photos/9328548/pexels-photo-9328548.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes Elegantes Carey Claro",
      brand: "Gucci",
      price: 459900,
      material: "Acetato",
      shape: "Cat Eye",
      categories: ["Marcos ópticos", "Mujer", "Premium"],
      badge: "OFERTA",
    },
    {
      id: "36",
      imageUrl:
        "https://images.pexels.com/photos/32398468/pexels-photo-32398468.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Gafas de Sol Minimalista Metálica",
      brand: "Vogue",
      price: 199900,
      material: "Metal",
      shape: "Rectangular",
      categories: ["Gafas de sol", "Unisex"],
    },
    {
      id: "37",
      imageUrl:
        "https://images.pexels.com/photos/4324242/pexels-photo-4324242.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes Redondos Vintage Carey",
      brand: "Ray-Ban",
      price: 329900,
      material: "Acetato",
      shape: "Circular",
      categories: ["Marcos ópticos", "Unisex", "Premium"],
      badge: "NUEVO",
    },
    {
      id: "38",
      imageUrl:
        "https://images.pexels.com/photos/5752242/pexels-photo-5752242.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Gafas Aviador Espejado Azul",
      brand: "Prada",
      price: 419900,
      material: "Metal",
      shape: "Aviador",
      categories: ["Gafas de sol", "Hombre", "Deportivas"],
    },
    {
      id: "39",
      imageUrl:
        "https://images.pexels.com/photos/6571507/pexels-photo-6571507.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Marcos Ópticos Ovalados Dorado",
      brand: "Gucci",
      price: 539900,
      material: "Titanio",
      shape: "Circular",
      categories: ["Marcos ópticos", "Mujer", "Premium"],
    },
    {
      id: "40",
      imageUrl:
        "https://images.pexels.com/photos/4226865/pexels-photo-4226865.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes de Sol Cat Eye Rojo",
      brand: "Vogue",
      price: 289900,
      material: "Acetato",
      shape: "Cat Eye",
      categories: ["Gafas de sol", "Mujer"],
      badge: "OFERTA",
    },
    {
      id: "41",
      imageUrl:
        "https://images.pexels.com/photos/28616331/pexels-photo-28616331.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Gafas Deportivas Polarizadas Negro",
      brand: "Oakley",
      price: 609900,
      material: "Titanio",
      shape: "Rectangular",
      categories: ["Gafas de sol", "Deportivas", "Unisex"],
      badge: "NUEVO",
    },
    {
      id: "42",
      imageUrl:
        "https://images.pexels.com/photos/26050120/pexels-photo-26050120.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes Rectangulares Metálicos Negro",
      brand: "Persol",
      price: 349900,
      material: "Metal",
      shape: "Rectangular",
      categories: ["Marcos ópticos", "Hombre"],
    },
    {
      id: "43",
      imageUrl:
        "https://images.pexels.com/photos/28488304/pexels-photo-28488304.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Gafas de Sol Clásicas Carey",
      brand: "Ray-Ban",
      price: 359900,
      material: "Acetato",
      shape: "Rectangular",
      categories: ["Gafas de sol", "Unisex", "Premium"],
    },
    {
      id: "44",
      imageUrl:
        "https://images.pexels.com/photos/5202050/pexels-photo-5202050.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Marcos Ópticos Redondos Transparente",
      brand: "Prada",
      price: 389900,
      material: "Acetato",
      shape: "Circular",
      categories: ["Marcos ópticos", "Unisex"],
      badge: "NUEVO",
    },
    {
      id: "45",
      imageUrl:
        "https://images.pexels.com/photos/7357970/pexels-photo-7357970.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Gafas Solares Oversized Carey",
      brand: "Gucci",
      price: 649900,
      material: "Acetato",
      shape: "Cat Eye",
      categories: ["Gafas de sol", "Mujer", "Premium"],
      badge: "OFERTA",
    },
    {
      id: "46",
      imageUrl:
        "https://images.pexels.com/photos/11651941/pexels-photo-11651941.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes Deportivos Ciclismo Rojo",
      brand: "Oakley",
      price: 529900,
      material: "Titanio",
      shape: "Rectangular",
      categories: ["Gafas de sol", "Deportivas", "Unisex"],
    },
    {
      id: "47",
      imageUrl:
        "https://images.pexels.com/photos/4687151/pexels-photo-4687151.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Gafas Aviador Plateado Brillante",
      brand: "Ray-Ban",
      price: 399900,
      material: "Metal",
      shape: "Aviador",
      categories: ["Gafas de sol", "Hombre", "Unisex"],
      badge: "NUEVO",
    },
    {
      id: "48",
      imageUrl:
        "https://images.pexels.com/photos/4037164/pexels-photo-4037164.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Marcos Ópticos Rectangulares Negro",
      brand: "Persol",
      price: 279900,
      material: "Acetato",
      shape: "Rectangular",
      categories: ["Marcos ópticos", "Unisex"],
    },
    {
      id: "49",
      imageUrl:
        "https://images.pexels.com/photos/6011443/pexels-photo-6011443.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Gafas de Sol Geométricas Dorado",
      brand: "Prada",
      price: 479900,
      material: "Metal",
      shape: "Rectangular",
      categories: ["Gafas de sol", "Mujer", "Premium"],
      badge: "OFERTA",
    },
    {
      id: "50",
      imageUrl:
        "https://images.pexels.com/photos/4037163/pexels-photo-4037163.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Lentes Redondos Metálicos Vintage",
      brand: "Vogue",
      price: 229900,
      material: "Metal",
      shape: "Circular",
      categories: ["Marcos ópticos", "Unisex"],
      badge: "NUEVO",
    },
  ]
}
