/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainLayoutRouteImport } from './routes/_main-layout'
import { Route as MainLayoutIndexRouteImport } from './routes/_main-layout/index'
import { Route as MainLayoutCategoriesRouteImport } from './routes/_main-layout/categories'
import { Route as MainLayoutCatalogRouteImport } from './routes/_main-layout/catalog'
import { Route as MainLayoutBrandsRouteImport } from './routes/_main-layout/brands'
import { Route as MainLayoutAppointmentsRouteImport } from './routes/_main-layout/appointments'
import { Route as MainLayoutAuthenticatedRouteImport } from './routes/_main-layout/_authenticated'
import { Route as MainLayoutProductIdRouteImport } from './routes/_main-layout/product.$id'
import { Route as MainLayoutAuthenticatedOrdersRouteImport } from './routes/_main-layout/_authenticated/orders'
import { Route as MainLayoutAuthenticatedMyaccountProfileRouteImport } from './routes/_main-layout/_authenticated/myaccount/profile'

const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_main-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutIndexRoute = MainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutCategoriesRoute = MainLayoutCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutCatalogRoute = MainLayoutCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutBrandsRoute = MainLayoutBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutAppointmentsRoute = MainLayoutAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutAuthenticatedRoute = MainLayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutProductIdRoute = MainLayoutProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutAuthenticatedOrdersRoute =
  MainLayoutAuthenticatedOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => MainLayoutAuthenticatedRoute,
  } as any)
const MainLayoutAuthenticatedMyaccountProfileRoute =
  MainLayoutAuthenticatedMyaccountProfileRouteImport.update({
    id: '/myaccount/profile',
    path: '/myaccount/profile',
    getParentRoute: () => MainLayoutAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainLayoutIndexRoute
  '/appointments': typeof MainLayoutAppointmentsRoute
  '/brands': typeof MainLayoutBrandsRoute
  '/catalog': typeof MainLayoutCatalogRoute
  '/categories': typeof MainLayoutCategoriesRoute
  '/orders': typeof MainLayoutAuthenticatedOrdersRoute
  '/product/$id': typeof MainLayoutProductIdRoute
  '/myaccount/profile': typeof MainLayoutAuthenticatedMyaccountProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof MainLayoutIndexRoute
  '/appointments': typeof MainLayoutAppointmentsRoute
  '/brands': typeof MainLayoutBrandsRoute
  '/catalog': typeof MainLayoutCatalogRoute
  '/categories': typeof MainLayoutCategoriesRoute
  '/orders': typeof MainLayoutAuthenticatedOrdersRoute
  '/product/$id': typeof MainLayoutProductIdRoute
  '/myaccount/profile': typeof MainLayoutAuthenticatedMyaccountProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main-layout': typeof MainLayoutRouteWithChildren
  '/_main-layout/_authenticated': typeof MainLayoutAuthenticatedRouteWithChildren
  '/_main-layout/appointments': typeof MainLayoutAppointmentsRoute
  '/_main-layout/brands': typeof MainLayoutBrandsRoute
  '/_main-layout/catalog': typeof MainLayoutCatalogRoute
  '/_main-layout/categories': typeof MainLayoutCategoriesRoute
  '/_main-layout/': typeof MainLayoutIndexRoute
  '/_main-layout/_authenticated/orders': typeof MainLayoutAuthenticatedOrdersRoute
  '/_main-layout/product/$id': typeof MainLayoutProductIdRoute
  '/_main-layout/_authenticated/myaccount/profile': typeof MainLayoutAuthenticatedMyaccountProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/brands'
    | '/catalog'
    | '/categories'
    | '/orders'
    | '/product/$id'
    | '/myaccount/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/brands'
    | '/catalog'
    | '/categories'
    | '/orders'
    | '/product/$id'
    | '/myaccount/profile'
  id:
    | '__root__'
    | '/_main-layout'
    | '/_main-layout/_authenticated'
    | '/_main-layout/appointments'
    | '/_main-layout/brands'
    | '/_main-layout/catalog'
    | '/_main-layout/categories'
    | '/_main-layout/'
    | '/_main-layout/_authenticated/orders'
    | '/_main-layout/product/$id'
    | '/_main-layout/_authenticated/myaccount/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main-layout': {
      id: '/_main-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main-layout/': {
      id: '/_main-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/categories': {
      id: '/_main-layout/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof MainLayoutCategoriesRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/catalog': {
      id: '/_main-layout/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof MainLayoutCatalogRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/brands': {
      id: '/_main-layout/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof MainLayoutBrandsRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/appointments': {
      id: '/_main-layout/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof MainLayoutAppointmentsRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/_authenticated': {
      id: '/_main-layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutAuthenticatedRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/product/$id': {
      id: '/_main-layout/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof MainLayoutProductIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/_authenticated/orders': {
      id: '/_main-layout/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof MainLayoutAuthenticatedOrdersRouteImport
      parentRoute: typeof MainLayoutAuthenticatedRoute
    }
    '/_main-layout/_authenticated/myaccount/profile': {
      id: '/_main-layout/_authenticated/myaccount/profile'
      path: '/myaccount/profile'
      fullPath: '/myaccount/profile'
      preLoaderRoute: typeof MainLayoutAuthenticatedMyaccountProfileRouteImport
      parentRoute: typeof MainLayoutAuthenticatedRoute
    }
  }
}

interface MainLayoutAuthenticatedRouteChildren {
  MainLayoutAuthenticatedOrdersRoute: typeof MainLayoutAuthenticatedOrdersRoute
  MainLayoutAuthenticatedMyaccountProfileRoute: typeof MainLayoutAuthenticatedMyaccountProfileRoute
}

const MainLayoutAuthenticatedRouteChildren: MainLayoutAuthenticatedRouteChildren =
  {
    MainLayoutAuthenticatedOrdersRoute: MainLayoutAuthenticatedOrdersRoute,
    MainLayoutAuthenticatedMyaccountProfileRoute:
      MainLayoutAuthenticatedMyaccountProfileRoute,
  }

const MainLayoutAuthenticatedRouteWithChildren =
  MainLayoutAuthenticatedRoute._addFileChildren(
    MainLayoutAuthenticatedRouteChildren,
  )

interface MainLayoutRouteChildren {
  MainLayoutAuthenticatedRoute: typeof MainLayoutAuthenticatedRouteWithChildren
  MainLayoutAppointmentsRoute: typeof MainLayoutAppointmentsRoute
  MainLayoutBrandsRoute: typeof MainLayoutBrandsRoute
  MainLayoutCatalogRoute: typeof MainLayoutCatalogRoute
  MainLayoutCategoriesRoute: typeof MainLayoutCategoriesRoute
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
  MainLayoutProductIdRoute: typeof MainLayoutProductIdRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutAuthenticatedRoute: MainLayoutAuthenticatedRouteWithChildren,
  MainLayoutAppointmentsRoute: MainLayoutAppointmentsRoute,
  MainLayoutBrandsRoute: MainLayoutBrandsRoute,
  MainLayoutCatalogRoute: MainLayoutCatalogRoute,
  MainLayoutCategoriesRoute: MainLayoutCategoriesRoute,
  MainLayoutIndexRoute: MainLayoutIndexRoute,
  MainLayoutProductIdRoute: MainLayoutProductIdRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainLayoutRoute: MainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
