/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainLayoutRouteImport } from './routes/_main-layout'
import { Route as MainLayoutIndexRouteImport } from './routes/_main-layout/index'
import { Route as MainLayoutCatalogRouteImport } from './routes/_main-layout/catalog'
import { Route as MainLayoutApointmentsRouteImport } from './routes/_main-layout/apointments'
import { Route as MainLayoutAuthenticatedRouteImport } from './routes/_main-layout/_authenticated'
import { Route as MainLayoutAuthenticatedOrdersRouteImport } from './routes/_main-layout/_authenticated/orders'
import { Route as MainLayoutAuthenticatedMyaccountProfileRouteImport } from './routes/_main-layout/_authenticated/myaccount/profile'

const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_main-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutIndexRoute = MainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutCatalogRoute = MainLayoutCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutApointmentsRoute = MainLayoutApointmentsRouteImport.update({
  id: '/apointments',
  path: '/apointments',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutAuthenticatedRoute = MainLayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutAuthenticatedOrdersRoute =
  MainLayoutAuthenticatedOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => MainLayoutAuthenticatedRoute,
  } as any)
const MainLayoutAuthenticatedMyaccountProfileRoute =
  MainLayoutAuthenticatedMyaccountProfileRouteImport.update({
    id: '/myaccount/profile',
    path: '/myaccount/profile',
    getParentRoute: () => MainLayoutAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainLayoutIndexRoute
  '/apointments': typeof MainLayoutApointmentsRoute
  '/catalog': typeof MainLayoutCatalogRoute
  '/orders': typeof MainLayoutAuthenticatedOrdersRoute
  '/myaccount/profile': typeof MainLayoutAuthenticatedMyaccountProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof MainLayoutIndexRoute
  '/apointments': typeof MainLayoutApointmentsRoute
  '/catalog': typeof MainLayoutCatalogRoute
  '/orders': typeof MainLayoutAuthenticatedOrdersRoute
  '/myaccount/profile': typeof MainLayoutAuthenticatedMyaccountProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main-layout': typeof MainLayoutRouteWithChildren
  '/_main-layout/_authenticated': typeof MainLayoutAuthenticatedRouteWithChildren
  '/_main-layout/apointments': typeof MainLayoutApointmentsRoute
  '/_main-layout/catalog': typeof MainLayoutCatalogRoute
  '/_main-layout/': typeof MainLayoutIndexRoute
  '/_main-layout/_authenticated/orders': typeof MainLayoutAuthenticatedOrdersRoute
  '/_main-layout/_authenticated/myaccount/profile': typeof MainLayoutAuthenticatedMyaccountProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apointments'
    | '/catalog'
    | '/orders'
    | '/myaccount/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apointments' | '/catalog' | '/orders' | '/myaccount/profile'
  id:
    | '__root__'
    | '/_main-layout'
    | '/_main-layout/_authenticated'
    | '/_main-layout/apointments'
    | '/_main-layout/catalog'
    | '/_main-layout/'
    | '/_main-layout/_authenticated/orders'
    | '/_main-layout/_authenticated/myaccount/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main-layout': {
      id: '/_main-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main-layout/': {
      id: '/_main-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/catalog': {
      id: '/_main-layout/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof MainLayoutCatalogRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/apointments': {
      id: '/_main-layout/apointments'
      path: '/apointments'
      fullPath: '/apointments'
      preLoaderRoute: typeof MainLayoutApointmentsRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/_authenticated': {
      id: '/_main-layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutAuthenticatedRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/_authenticated/orders': {
      id: '/_main-layout/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof MainLayoutAuthenticatedOrdersRouteImport
      parentRoute: typeof MainLayoutAuthenticatedRoute
    }
    '/_main-layout/_authenticated/myaccount/profile': {
      id: '/_main-layout/_authenticated/myaccount/profile'
      path: '/myaccount/profile'
      fullPath: '/myaccount/profile'
      preLoaderRoute: typeof MainLayoutAuthenticatedMyaccountProfileRouteImport
      parentRoute: typeof MainLayoutAuthenticatedRoute
    }
  }
}

interface MainLayoutAuthenticatedRouteChildren {
  MainLayoutAuthenticatedOrdersRoute: typeof MainLayoutAuthenticatedOrdersRoute
  MainLayoutAuthenticatedMyaccountProfileRoute: typeof MainLayoutAuthenticatedMyaccountProfileRoute
}

const MainLayoutAuthenticatedRouteChildren: MainLayoutAuthenticatedRouteChildren =
  {
    MainLayoutAuthenticatedOrdersRoute: MainLayoutAuthenticatedOrdersRoute,
    MainLayoutAuthenticatedMyaccountProfileRoute:
      MainLayoutAuthenticatedMyaccountProfileRoute,
  }

const MainLayoutAuthenticatedRouteWithChildren =
  MainLayoutAuthenticatedRoute._addFileChildren(
    MainLayoutAuthenticatedRouteChildren,
  )

interface MainLayoutRouteChildren {
  MainLayoutAuthenticatedRoute: typeof MainLayoutAuthenticatedRouteWithChildren
  MainLayoutApointmentsRoute: typeof MainLayoutApointmentsRoute
  MainLayoutCatalogRoute: typeof MainLayoutCatalogRoute
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutAuthenticatedRoute: MainLayoutAuthenticatedRouteWithChildren,
  MainLayoutApointmentsRoute: MainLayoutApointmentsRoute,
  MainLayoutCatalogRoute: MainLayoutCatalogRoute,
  MainLayoutIndexRoute: MainLayoutIndexRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainLayoutRoute: MainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
