/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as MainLayoutRouteImport } from './routes/_main-layout'
import { Route as MainLayoutIndexRouteImport } from './routes/_main-layout/index'
import { Route as MainLayoutCategoriesRouteImport } from './routes/_main-layout/categories'
import { Route as MainLayoutCatalogRouteImport } from './routes/_main-layout/catalog'
import { Route as MainLayoutBrandsRouteImport } from './routes/_main-layout/brands'
import { Route as MainLayoutAppointmentsRouteImport } from './routes/_main-layout/appointments'
import { Route as MainLayoutAuthenticatedRouteImport } from './routes/_main-layout/_authenticated'
import { Route as MainLayoutProductIdRouteImport } from './routes/_main-layout/product.$id'
import { Route as MainLayoutAuthenticatedMyaccountRouteImport } from './routes/_main-layout/_authenticated/myaccount'
import { Route as MainLayoutAuthenticatedCheckoutRouteImport } from './routes/_main-layout/_authenticated/checkout'
import { Route as MainLayoutAuthenticatedCartRouteImport } from './routes/_main-layout/_authenticated/cart'
import { Route as MainLayoutAuthenticatedMyaccountProfileRouteImport } from './routes/_main-layout/_authenticated/myaccount/profile'
import { Route as MainLayoutAuthenticatedMyaccountOrdersRouteImport } from './routes/_main-layout/_authenticated/myaccount/orders'
import { Route as MainLayoutAuthenticatedMyaccountAppointmentsRouteImport } from './routes/_main-layout/_authenticated/myaccount/appointments'
import { Route as MainLayoutAuthenticatedMyaccountAddressesRouteImport } from './routes/_main-layout/_authenticated/myaccount/addresses'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_main-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutIndexRoute = MainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutCategoriesRoute = MainLayoutCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutCatalogRoute = MainLayoutCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutBrandsRoute = MainLayoutBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutAppointmentsRoute = MainLayoutAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutAuthenticatedRoute = MainLayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutProductIdRoute = MainLayoutProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => MainLayoutRoute,
} as any)
const MainLayoutAuthenticatedMyaccountRoute =
  MainLayoutAuthenticatedMyaccountRouteImport.update({
    id: '/myaccount',
    path: '/myaccount',
    getParentRoute: () => MainLayoutAuthenticatedRoute,
  } as any)
const MainLayoutAuthenticatedCheckoutRoute =
  MainLayoutAuthenticatedCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => MainLayoutAuthenticatedRoute,
  } as any)
const MainLayoutAuthenticatedCartRoute =
  MainLayoutAuthenticatedCartRouteImport.update({
    id: '/cart',
    path: '/cart',
    getParentRoute: () => MainLayoutAuthenticatedRoute,
  } as any)
const MainLayoutAuthenticatedMyaccountProfileRoute =
  MainLayoutAuthenticatedMyaccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => MainLayoutAuthenticatedMyaccountRoute,
  } as any)
const MainLayoutAuthenticatedMyaccountOrdersRoute =
  MainLayoutAuthenticatedMyaccountOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => MainLayoutAuthenticatedMyaccountRoute,
  } as any)
const MainLayoutAuthenticatedMyaccountAppointmentsRoute =
  MainLayoutAuthenticatedMyaccountAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => MainLayoutAuthenticatedMyaccountRoute,
  } as any)
const MainLayoutAuthenticatedMyaccountAddressesRoute =
  MainLayoutAuthenticatedMyaccountAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => MainLayoutAuthenticatedMyaccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainLayoutIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/appointments': typeof MainLayoutAppointmentsRoute
  '/brands': typeof MainLayoutBrandsRoute
  '/catalog': typeof MainLayoutCatalogRoute
  '/categories': typeof MainLayoutCategoriesRoute
  '/cart': typeof MainLayoutAuthenticatedCartRoute
  '/checkout': typeof MainLayoutAuthenticatedCheckoutRoute
  '/myaccount': typeof MainLayoutAuthenticatedMyaccountRouteWithChildren
  '/product/$id': typeof MainLayoutProductIdRoute
  '/myaccount/addresses': typeof MainLayoutAuthenticatedMyaccountAddressesRoute
  '/myaccount/appointments': typeof MainLayoutAuthenticatedMyaccountAppointmentsRoute
  '/myaccount/orders': typeof MainLayoutAuthenticatedMyaccountOrdersRoute
  '/myaccount/profile': typeof MainLayoutAuthenticatedMyaccountProfileRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/': typeof MainLayoutIndexRoute
  '/appointments': typeof MainLayoutAppointmentsRoute
  '/brands': typeof MainLayoutBrandsRoute
  '/catalog': typeof MainLayoutCatalogRoute
  '/categories': typeof MainLayoutCategoriesRoute
  '/cart': typeof MainLayoutAuthenticatedCartRoute
  '/checkout': typeof MainLayoutAuthenticatedCheckoutRoute
  '/myaccount': typeof MainLayoutAuthenticatedMyaccountRouteWithChildren
  '/product/$id': typeof MainLayoutProductIdRoute
  '/myaccount/addresses': typeof MainLayoutAuthenticatedMyaccountAddressesRoute
  '/myaccount/appointments': typeof MainLayoutAuthenticatedMyaccountAppointmentsRoute
  '/myaccount/orders': typeof MainLayoutAuthenticatedMyaccountOrdersRoute
  '/myaccount/profile': typeof MainLayoutAuthenticatedMyaccountProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main-layout': typeof MainLayoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_main-layout/_authenticated': typeof MainLayoutAuthenticatedRouteWithChildren
  '/_main-layout/appointments': typeof MainLayoutAppointmentsRoute
  '/_main-layout/brands': typeof MainLayoutBrandsRoute
  '/_main-layout/catalog': typeof MainLayoutCatalogRoute
  '/_main-layout/categories': typeof MainLayoutCategoriesRoute
  '/_main-layout/': typeof MainLayoutIndexRoute
  '/_main-layout/_authenticated/cart': typeof MainLayoutAuthenticatedCartRoute
  '/_main-layout/_authenticated/checkout': typeof MainLayoutAuthenticatedCheckoutRoute
  '/_main-layout/_authenticated/myaccount': typeof MainLayoutAuthenticatedMyaccountRouteWithChildren
  '/_main-layout/product/$id': typeof MainLayoutProductIdRoute
  '/_main-layout/_authenticated/myaccount/addresses': typeof MainLayoutAuthenticatedMyaccountAddressesRoute
  '/_main-layout/_authenticated/myaccount/appointments': typeof MainLayoutAuthenticatedMyaccountAppointmentsRoute
  '/_main-layout/_authenticated/myaccount/orders': typeof MainLayoutAuthenticatedMyaccountOrdersRoute
  '/_main-layout/_authenticated/myaccount/profile': typeof MainLayoutAuthenticatedMyaccountProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/appointments'
    | '/brands'
    | '/catalog'
    | '/categories'
    | '/cart'
    | '/checkout'
    | '/myaccount'
    | '/product/$id'
    | '/myaccount/addresses'
    | '/myaccount/appointments'
    | '/myaccount/orders'
    | '/myaccount/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/'
    | '/appointments'
    | '/brands'
    | '/catalog'
    | '/categories'
    | '/cart'
    | '/checkout'
    | '/myaccount'
    | '/product/$id'
    | '/myaccount/addresses'
    | '/myaccount/appointments'
    | '/myaccount/orders'
    | '/myaccount/profile'
  id:
    | '__root__'
    | '/_main-layout'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_main-layout/_authenticated'
    | '/_main-layout/appointments'
    | '/_main-layout/brands'
    | '/_main-layout/catalog'
    | '/_main-layout/categories'
    | '/_main-layout/'
    | '/_main-layout/_authenticated/cart'
    | '/_main-layout/_authenticated/checkout'
    | '/_main-layout/_authenticated/myaccount'
    | '/_main-layout/product/$id'
    | '/_main-layout/_authenticated/myaccount/addresses'
    | '/_main-layout/_authenticated/myaccount/appointments'
    | '/_main-layout/_authenticated/myaccount/orders'
    | '/_main-layout/_authenticated/myaccount/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main-layout': {
      id: '/_main-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main-layout/': {
      id: '/_main-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutIndexRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/categories': {
      id: '/_main-layout/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof MainLayoutCategoriesRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/catalog': {
      id: '/_main-layout/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof MainLayoutCatalogRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/brands': {
      id: '/_main-layout/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof MainLayoutBrandsRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/appointments': {
      id: '/_main-layout/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof MainLayoutAppointmentsRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/_authenticated': {
      id: '/_main-layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutAuthenticatedRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/product/$id': {
      id: '/_main-layout/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof MainLayoutProductIdRouteImport
      parentRoute: typeof MainLayoutRoute
    }
    '/_main-layout/_authenticated/myaccount': {
      id: '/_main-layout/_authenticated/myaccount'
      path: '/myaccount'
      fullPath: '/myaccount'
      preLoaderRoute: typeof MainLayoutAuthenticatedMyaccountRouteImport
      parentRoute: typeof MainLayoutAuthenticatedRoute
    }
    '/_main-layout/_authenticated/checkout': {
      id: '/_main-layout/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof MainLayoutAuthenticatedCheckoutRouteImport
      parentRoute: typeof MainLayoutAuthenticatedRoute
    }
    '/_main-layout/_authenticated/cart': {
      id: '/_main-layout/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof MainLayoutAuthenticatedCartRouteImport
      parentRoute: typeof MainLayoutAuthenticatedRoute
    }
    '/_main-layout/_authenticated/myaccount/profile': {
      id: '/_main-layout/_authenticated/myaccount/profile'
      path: '/profile'
      fullPath: '/myaccount/profile'
      preLoaderRoute: typeof MainLayoutAuthenticatedMyaccountProfileRouteImport
      parentRoute: typeof MainLayoutAuthenticatedMyaccountRoute
    }
    '/_main-layout/_authenticated/myaccount/orders': {
      id: '/_main-layout/_authenticated/myaccount/orders'
      path: '/orders'
      fullPath: '/myaccount/orders'
      preLoaderRoute: typeof MainLayoutAuthenticatedMyaccountOrdersRouteImport
      parentRoute: typeof MainLayoutAuthenticatedMyaccountRoute
    }
    '/_main-layout/_authenticated/myaccount/appointments': {
      id: '/_main-layout/_authenticated/myaccount/appointments'
      path: '/appointments'
      fullPath: '/myaccount/appointments'
      preLoaderRoute: typeof MainLayoutAuthenticatedMyaccountAppointmentsRouteImport
      parentRoute: typeof MainLayoutAuthenticatedMyaccountRoute
    }
    '/_main-layout/_authenticated/myaccount/addresses': {
      id: '/_main-layout/_authenticated/myaccount/addresses'
      path: '/addresses'
      fullPath: '/myaccount/addresses'
      preLoaderRoute: typeof MainLayoutAuthenticatedMyaccountAddressesRouteImport
      parentRoute: typeof MainLayoutAuthenticatedMyaccountRoute
    }
  }
}

interface MainLayoutAuthenticatedMyaccountRouteChildren {
  MainLayoutAuthenticatedMyaccountAddressesRoute: typeof MainLayoutAuthenticatedMyaccountAddressesRoute
  MainLayoutAuthenticatedMyaccountAppointmentsRoute: typeof MainLayoutAuthenticatedMyaccountAppointmentsRoute
  MainLayoutAuthenticatedMyaccountOrdersRoute: typeof MainLayoutAuthenticatedMyaccountOrdersRoute
  MainLayoutAuthenticatedMyaccountProfileRoute: typeof MainLayoutAuthenticatedMyaccountProfileRoute
}

const MainLayoutAuthenticatedMyaccountRouteChildren: MainLayoutAuthenticatedMyaccountRouteChildren =
  {
    MainLayoutAuthenticatedMyaccountAddressesRoute:
      MainLayoutAuthenticatedMyaccountAddressesRoute,
    MainLayoutAuthenticatedMyaccountAppointmentsRoute:
      MainLayoutAuthenticatedMyaccountAppointmentsRoute,
    MainLayoutAuthenticatedMyaccountOrdersRoute:
      MainLayoutAuthenticatedMyaccountOrdersRoute,
    MainLayoutAuthenticatedMyaccountProfileRoute:
      MainLayoutAuthenticatedMyaccountProfileRoute,
  }

const MainLayoutAuthenticatedMyaccountRouteWithChildren =
  MainLayoutAuthenticatedMyaccountRoute._addFileChildren(
    MainLayoutAuthenticatedMyaccountRouteChildren,
  )

interface MainLayoutAuthenticatedRouteChildren {
  MainLayoutAuthenticatedCartRoute: typeof MainLayoutAuthenticatedCartRoute
  MainLayoutAuthenticatedCheckoutRoute: typeof MainLayoutAuthenticatedCheckoutRoute
  MainLayoutAuthenticatedMyaccountRoute: typeof MainLayoutAuthenticatedMyaccountRouteWithChildren
}

const MainLayoutAuthenticatedRouteChildren: MainLayoutAuthenticatedRouteChildren =
  {
    MainLayoutAuthenticatedCartRoute: MainLayoutAuthenticatedCartRoute,
    MainLayoutAuthenticatedCheckoutRoute: MainLayoutAuthenticatedCheckoutRoute,
    MainLayoutAuthenticatedMyaccountRoute:
      MainLayoutAuthenticatedMyaccountRouteWithChildren,
  }

const MainLayoutAuthenticatedRouteWithChildren =
  MainLayoutAuthenticatedRoute._addFileChildren(
    MainLayoutAuthenticatedRouteChildren,
  )

interface MainLayoutRouteChildren {
  MainLayoutAuthenticatedRoute: typeof MainLayoutAuthenticatedRouteWithChildren
  MainLayoutAppointmentsRoute: typeof MainLayoutAppointmentsRoute
  MainLayoutBrandsRoute: typeof MainLayoutBrandsRoute
  MainLayoutCatalogRoute: typeof MainLayoutCatalogRoute
  MainLayoutCategoriesRoute: typeof MainLayoutCategoriesRoute
  MainLayoutIndexRoute: typeof MainLayoutIndexRoute
  MainLayoutProductIdRoute: typeof MainLayoutProductIdRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutAuthenticatedRoute: MainLayoutAuthenticatedRouteWithChildren,
  MainLayoutAppointmentsRoute: MainLayoutAppointmentsRoute,
  MainLayoutBrandsRoute: MainLayoutBrandsRoute,
  MainLayoutCatalogRoute: MainLayoutCatalogRoute,
  MainLayoutCategoriesRoute: MainLayoutCategoriesRoute,
  MainLayoutIndexRoute: MainLayoutIndexRoute,
  MainLayoutProductIdRoute: MainLayoutProductIdRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainLayoutRoute: MainLayoutRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
